version: '3.8'

services:
  mongo-staging:
    image: mongo
    container_name: mongo-staging
    ports:
      - "27018:27017"
    volumes:
      - mongo_staging_data:/data/db

  app-staging:
    build: .
    container_name: irrigation-app-staging
    ports:
      - "8081:8080"
    depends_on:
      - mongo-staging
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-staging:27017/irrigation-staging-db

volumes:
  mongo_staging_data:
