version: '3.8'

services:
  mongo-prod:
    image: mongo
    container_name: mongo-prod
    ports:
      - "27019:27017"
    volumes:
      - mongo_prod_data:/data/db

  app-prod:
    build: .
    container_name: irrigation-app-prod
    ports:
      - "8082:8080"
    depends_on:
      - mongo-prod
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-prod:27017/irrigation-prod-db

volumes:
  mongo_prod_data:
